create table
  public.users (
    id uuid not null default gen_random_uuid (),
    email text not null default ''::text,
    created_at timestamp with time zone not null default now(),
    username text not null,
    constraint users_pkey primary key (id),
    constraint users_email_key unique (email),
    constraint users_id_key unique (id),
    constraint users_username_key unique (username),
    constraint users_id_fkey foreign key (id) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.recipes (
    id bigint generated by default as identity,
    title text not null default ''::text,
    description text null default ''::text,
    steps text not null default ''::text,
    category text null default ''::text,
    created_at timestamp with time zone not null default now(),
    sustainability_info text not null default ''::text,
    user_generated boolean null,
    constraint recipes_pkey primary key (id),
    constraint recipes_id_key unique (id)
  ) tablespace pg_default;

create table
  public.ingredients_library (
    id bigint generated by default as identity,
    name text not null default ''::text,
    availability text null default ''::text,
    created_at timestamp with time zone not null default now(),
    constraint ingredients_library_pkey primary key (id),
    constraint ingredients_library_id_key unique (id)
  ) tablespace pg_default;


create table
  public.recipe_ingredients (
    id bigint generated by default as identity,
    recipe_id bigint not null,
    ingredient_id bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint recipe_ingredients_pkey primary key (id),
    constraint recipe_ingredients_id_key unique (id),
    constraint recipe_ingredients_ingredient_id_fkey foreign key (ingredient_id) references ingredients_library (id) on update cascade on delete cascade,
    constraint recipe_ingredients_recipe_id_fkey foreign key (recipe_id) references recipes (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.plans (
    id bigint generated by default as identity,
    meal_plan bigint not null,
    days text not null,
    recipes bigint not null,
    times text null default ''::text,
    created_at timestamp with time zone not null default now(),
    constraint plans_pkey primary key (id),
    constraint plans_id_key unique (id)
    -- constraint plans_meal_plan_fkey foreign key (meal_plan) references meal_plans (id) on update cascade on delete cascade,
    -- constraint plans_recipes_fkey foreign key (recipes) references recipe_plans (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.meal_plans (
    id bigint generated by default as identity,
    user_id uuid not null,
    plan bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint meal_plans_pkey primary key (id),
    constraint meal_plans_plan_fkey foreign key (plan) references plans (id) on update cascade on delete cascade,
    constraint meal_plans_user_id_fkey foreign key (user_id) references users (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.recipe_plans (
    id bigint generated by default as identity,
    plan_id bigint not null,
    recipe_id bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint recipe_plans_pkey primary key (id),
    constraint recipe_plans_id_key unique (id),
    constraint recipe_plans_plan_id_fkey foreign key (plan_id) references plans (id) on update cascade on delete cascade,
    constraint recipe_plans_recipe_id_fkey foreign key (recipe_id) references recipes (id) on update cascade on delete cascade
  ) tablespace pg_default;